CREATE DATABASE IF NOT EXISTS gcpos CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE gcpos;

CREATE TABLE IF NOT EXISTS LoginTables (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LoginName VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL,
    Email VARCHAR(200) DEFAULT '',
    CreateTime DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS gc_user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user VARCHAR(100) NOT NULL UNIQUE,
    pass VARCHAR(100) NOT NULL,
    xu INT DEFAULT 0,
    gem INT DEFAULT 0,
    email VARCHAR(200) DEFAULT '',
    createTime DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS gc_info (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) DEFAULT 'JX1 Game',
    urlgame TEXT,
    page VARCHAR(255) DEFAULT '',
    code TEXT,
    email VARCHAR(200) DEFAULT '',
    keyapi VARCHAR(255) DEFAULT '',
    khuyenmai TEXT,
    atmbank TEXT,
    momo TEXT
) ENGINE=InnoDB;

INSERT IGNORE INTO gc_info (id, title) VALUES (1, 'JX1 Game Portal');

CREATE TABLE IF NOT EXISTS gc_admin (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

-- Mật khẩu mặc định: admin123
INSERT IGNORE INTO gc_admin (username, password) VALUES ('admin', MD5('admin123'));

CREATE TABLE IF NOT EXISTS gc_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user VARCHAR(100),
    seri VARCHAR(200),
    pin VARCHAR(200),
    type VARCHAR(50),
    menhgia INT DEFAULT 0,
    status TINYINT DEFAULT 0,
    gia TINYINT DEFAULT 0,
    createTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    date DATE DEFAULT (CURRENT_DATE)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS gc_logxu (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user VARCHAR(100),
    xutru INT DEFAULT 0,
    createTime DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS gc_logcongxu (
    id INT AUTO_INCREMENT PRIMARY KEY,
    admin VARCHAR(100),
    user VARCHAR(100),
    xucong INT DEFAULT 0,
    createTime DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS gc_shop (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    xu INT DEFAULT 0,
    data VARCHAR(255) DEFAULT ''
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS gc_server (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sid INT,
    name VARCHAR(100),
    db_name VARCHAR(100)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS KTCoins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    UserName VARCHAR(100),
    KCoin INT DEFAULT 0,
    UpdateTime DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
